### ISSUE TITLE
Make Cookie & privacy statement clear

### ISSUE THREAD

**Issue by czervenka** [windingtree/homepage#252]
The web page currently informs users that it is collecting (beside others) targeting, advertising and functional cookies and there is no opt-out option.

Do we really need such long and unspecific cookie policy? As to my knowledge, the page stores only Google Analytics and CloudFlare cookie. Couldn't we just write something like: "We are using Google Analytics to understand how our visitors use this web site and CloudFlare to make this website load quickly for you." and add links to [Google Analytics opt-out plugin](https://tools.google.com/dlpage/gaoptout) and to explanation [how CloudFlare cookie is used](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-Cloudflare-cfduid-cookie-do-)?

**Comment by menschikov** [comment]
This is ok, there's no problem with it. We can be safe with current description. There's no proven benefits of changing the content of this block.

**Comment by czervenka** [comment]
@menschikov I didn't mean for risk of EU law incompatibility, I meant for risk of our reputation in decentralized society. Most people doesn't care about their privacy, but leaders in crypto world more probably would do ... they hopefully do :)

**Comment by menschikov** [comment]
@czervenka thanks, now understand your opinion)) But there's a common practice for landing pages with this notice. And today it is clear for most of mid-level internet users and especially for experienced ones (like crypto leaders). There's a risk of course but it's minimal, there's a common sense at the end, I don't think people  who interested in us will close the page because of that notice. I would not treat it as an issue for now, but I will include it to my list for future UX research.
